GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/4

###
DELETE http://localhost:3001/api/persons/4

###
Get http://localhost:3001/info

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Rest client",
  "number": "123"
}
